### ISSUE TITLE
Feature request: allow string formatting for values in subsets

### ISSUE THREAD

**Issue by slochower** [cbouy/mols2grid#10]
Hi, thanks again. 

It's really handy that you built-in CSS styling of the labels and tooltips, like `color: red`. It would also be great to support Python string formatting (e.g., to trim the string representation of floats). For example:

![image](https://user-images.githubusercontent.com/5393995/113339115-de01ff80-92de-11eb-9c24-bd3218b632bc.png)

I'm guessing this will be tricky since it looks like you're building up the CSS manually here: https://github.com/cbouy/mols2grid/blob/849cf49a105b941c3c6918bb4b91d9b4d348c4ed/mols2grid/molgrid.py#L316

...but I think it's something to consider for the future.

**Comment by cbouy** [comment]
Yes that would be a nice addition! 
However, I'll very likely put it outside of the `style` parameter for both clarity for users and simplicity on my side...
Something like this with a `fmt` parameter that works similarly to `style`:

![image](https://user-images.githubusercontent.com/27850535/113346393-14b63500-9334-11eb-9191-9a03217fb0d8.png)

**Comment by slochower** [comment]
Yep, that sounds like a good plan!

**Comment by fredrikw** [comment]
What do you think about also allowing callbacks? You could check in your "what would run internally" code if the format is a string or a callable and apply .format if its a string or otherwise just hand it over to apply. That way, the format could be very flexible.

**Comment by cbouy** [comment]
Now available in v0.0.5 with the `transform` parameter:
```python
transform={"Solubility": lambda x: f"{x:.2f}"}
```

**Comment by slochower** [comment]
Looks great! 🎉
