### ISSUE TITLE
Conda forge package available

### ISSUE THREAD

**Issue by hadim** [cbouy/mols2grid#14]
Hello @cbouy.

I just wanted to tell you that I have created a conda package for `mols2grid` at https://github.com/conda-forge/mols2grid-feedstock: `mamba install -c conda-forge mols2grid`.

Feel free to make a PR to the feedstock if you want to be added as a maintainer of the package.

---

As a side note, I am also the author of the `datamol` library (https://github.com/datamol-org/datamol), in case you want to use it in `mol2grid`. It also has a nice 3D conformer viewer that could potentially be added to `mol2grid`.

Close once you have read this, since this is not a real issue :-)

**Comment by cbouy** [comment]
Hi @hadim,

Thanks a lot for doing this!
I'm currently drowning in deadlines but as soon as I get some time I'll have a closer look and update the installation instructions ! 
How does it make a release though? Is it automatic from pip or github releases, or do you have to trigger them manually?
Thanks again!

Cédric

Ps: I'll leave the issue open as a personal reminder 😅

**Comment by hadim** [comment]
Releasing a new package on conda forge is automatic **if** the source used is coming from pypi (which is the case). A bot will just open a PR on the feedstock repo, run the CI and wait for a maintainer to review and merge it. Once merged the package is built automatically and made available.

It's also possible to do that manually by simply opening a PR on the feedstock repo.

More info at https://conda-forge.org/docs/maintainer/updating_pkgs.html

**Comment by cbouy** [comment]
Hey @hadim,
Thanks again for taking care of this!
Would it be possible to specify a minimal version for RDKit in the conda recipe ? `2020.03.1` should do it

**Comment by hadim** [comment]
Yup it's possible. See https://github.com/conda-forge/mols2grid-feedstock/pull/1

**Comment by cbouy** [comment]
Awesome, thanks! I've updated the readme with the new instructions.
Thanks again for taking care of this!

**Comment by hadim** [comment]
@cbouy also if you want to be added as a maintainer of the feedstock, feel free to ping me and I can do that.
