### ISSUE TITLE
AttributeError: partially initialized module 'mols2grid' has no attribute 'display' (most likely due to a circular import)

### ISSUE THREAD

**Issue by UnixJunkie** [cbouy/mols2grid#15]

**Comment by UnixJunkie** [comment]
I have never seen this error in my life.

Is it not OK to have 'import mols2grid' inside of some python source file?

Then just call mols2grid.display then mols2grid.save?

**Comment by UnixJunkie** [comment]
Ok, apparently, you either call display _OR_ save...
Not one then the other.

**Comment by UnixJunkie** [comment]
Ok, this error was due to having created a script itself called mols2grid, that was importing the mols2grid library.
Renaming this script sdf2grid, for example, solves this issue.

**Comment by cbouy** [comment]
Hey @UnixJunkie 

Glad you could solve this one by yourself!  
FYI there's currently a bug in `mols2grid.save` which makes it unusable but it will be fixed soon. In the meantime you'll have to use the `mols2grid.MolGrid` class if you want to save it as an HTML document.
