### ISSUE TITLE
Different MolGrid instances "share" .get_selection

### ISSUE THREAD

**Issue by bieniekmateusz** [cbouy/mols2grid#31]
Hello. We added one more MolGrid instance and it appears that the first MolGrid selection affects what is selected in the second MolGrid. 

```
import mols2grid

m1 = mols2grid.MolGrid()
m2 = mols2grid.MolGrid()

# select the first item on m1

m2.get_selection()
# shows the item selected with the index of m1
```

Version: mols2grid-0.2.2

I am bit busy now but I'll try to have a look in the near future.

**Comment by cbouy** [comment]
Hi @bieniekmateusz,

When you create the grids, you need to give them different names:

```python
m1 = mols2grid.MolGrid(name="m1")
m2 = mols2grid.MolGrid(name="m2")
```

This way the selections shouldn't overlap

**Comment by bieniekmateusz** [comment]
Thanks @cbouy , sadly that doesn't seem to have resolved my issue. I'll create a minimum example and share it here shortly.

**Comment by cbouy** [comment]
Great, thanks! I found where the bug comes from, the bugfix is now available on the `master` branch.
I'll try to release a new version next week with this change
