### ISSUE TITLE
Hover popup flickers

### ISSUE THREAD

**Issue by freewind2213** [cbouy/mols2grid#41]
When the hover popup to display info about molecule is higher than the frame size, the hover popup will keep flickering and not displays the info.

**Comment by freewind2213** [comment]
It works well on Windows 11, however on Mac os, it flickers when using Microsoft Edge or Safari.

**Comment by cbouy** [comment]
Hi @freewind2213,

I've noticed this issue and meant to address it in the last update but forgot, here are some workarounds:

- You can change the placement of the tooltip info with `tooltip_placement="auto"` (`"bottom"` by default, which causes the issue)
- You can change how this tooltip info is triggered with `tooltip_trigger`: by default it's `tooltip_trigger="hover click"` but you can switch it to just `"click"` if you don't plan on using the callback functionalities.

Hope that helps,

Cédric

**Comment by freewind2213** [comment]
Hi @cbouy ,

I set tooltip_placement="auto" and the problem is gone, thanks a lot.
