### ISSUE TITLE
Question: is there a way to label atoms? 

### ISSUE THREAD

**Issue by aced125** [cbouy/mols2grid#56]
This currently doesn't work for me. Example:

```python
import mols2grid
from rdkit import Chem

mol = Chem.MolFromSmiles("c1ccncc1")

for i, atom in enumerate(mol.GetAtoms()):
    atom.SetProp("molAtomMapNumber", str(atom.GetIdx()+1))
    atom.SetProp("atomNote", "hi")

mols2grid.display([mol])
```

<img width="254" alt="Screenshot 2023-08-11 at 23 34 02" src="https://github.com/cbouy/mols2grid/assets/44452903/7d9c871c-e6e3-4d7a-ab20-5982e02986a2">

**Comment by cbouy** [comment]
You need to prerender images in order to do that:

```python
mols2grid.display([mol], prerender=True)
```
Without this mols2grid will just use the SMILES string (which includes the atom map number in your example) to do the rendering browser-side which is faster.

Feel free to reopen the issue if you have another related question.

Cheers,
Cédric

**Comment by aced125** [comment]
thanks, appreciate that!
