### ISSUE TITLE
The orientation differs between image and mols2grid

### ISSUE THREAD

**Issue by khoroshyy** [cbouy/mols2grid#62]
![image](https://github.com/user-attachments/assets/42087d06-1dbc-4a46-8904-a47bd7c02f14)

**Comment by cbouy** [comment]
Try with `prerender=True, use_coords=True` to use directly the existing mols with their current coordinates for rendering

**Comment by cbouy** [comment]
I'll close the issue but feel free to reopen if it didn't work or you have other related questions

**Comment by khoroshyy** [comment]
![image](https://github.com/user-attachments/assets/503d41fe-2014-42ad-b963-3fa8356e2a6e)
Thanks.
It works.
